spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunti?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qing
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

logging:
  level:
    com.daiqi.yun: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-enums-package: com.daiqi.com.daiqi.yun.constant
